### ISSUE TITLE
Missing author ids in comments

### ISSUE THREAD

**Issue by micheleb** [kitemakerhq/dump-organization#2]
Hi there, thanks for the tool! 🙏🏻 

I noticed that in the JSON export that's generated, the `workItems[].comments` field has no way to link a comment with its author. I'm getting this:

```json
            {
              "id": "<comment id>",
              "body": "the comment\n",
              "threadId": "<some id>",
              "actor": {
                "__typename": "User"
              },
              "updatedAt": 1657202041395,
              "createdAt": 1657202041395,
              "__typename": "Comment"
            }
```
I guess what's missing is the `actor.id` field.
Would it be possible to add it?

**Comment by vallo87** [comment]
UP

**Comment by ksimons** [comment]
Hi, this has now been fixed.

**Comment by micheleb** [comment]
working now. Thanks! 🎉
